### PR TITLE
Unify master and PILOT container install CI jobs. Closes #66.

### LINKED ISSUE #66: Update pilot container automation jobs to pull latest pilot image
Update pilot container automation jobs to pull latest pilot image.

- Download the installer from pilot release
- Run installer
- Run install test

Should include Fedora 26, Fedora 27, Centos7,  RHEL 6 and RHEL 7 and should work in order to have a green build. Also both should be run no matter if the first one tried failed or not.

### PR DESCRIPTION
**Pull request by chambridge**

### CODE REVIEW

**Review by kdelee — APPROVED** [review]
:tada: Looks great.

Do you want me to push this to Jenkins or did you get your SSL issues worked out?

**Comment by kdelee** [comment]
Did just remember that we talked about deleting old pilot tests in this repo

**Comment by chambridge** [comment]
I can push. I made the SSL updates earlier.

**Comment by chambridge** [comment]
ok I can remove those too.

**Comment by chambridge** [comment]
```
INFO:jenkins_jobs.builder:Number of jobs generated:  10
INFO:jenkins_jobs.builder:Creating jenkins job qcs-PILOT-container-install-centos7
INFO:jenkins_jobs.builder:Creating jenkins job qcs-PILOT-container-install-f26
INFO:jenkins_jobs.builder:Reconfiguring jenkins job qcs-PILOT-container-install-f27
INFO:jenkins_jobs.builder:Reconfiguring jenkins job qcs-PILOT-container-install-rhel6
INFO:jenkins_jobs.builder:Reconfiguring jenkins job qcs-PILOT-container-install-rhel7
INFO:jenkins_jobs.builder:Reconfiguring jenkins job qcs-master-container-install-centos7
INFO:jenkins_jobs.builder:Reconfiguring jenkins job qcs-master-container-install-f26
INFO:jenkins_jobs.builder:Reconfiguring jenkins job qcs-master-container-install-f27
INFO:jenkins_jobs.builder:Reconfiguring jenkins job qcs-master-container-install-rhel6
INFO:jenkins_jobs.builder:Reconfiguring jenkins job qcs-master-container-install-rhel7
INFO:jenkins_jobs.cli.subcommand.update:Number of jobs updated: 10
```

**Pull request merged**
