### PR TITLE
Update name references from 'qcs' to 'qpc'. Closes #70.

### LINKED ISSUE #70: Update qcs references to qpc
# Issue type
- Other

# Description of issue
We inconsistently reference **quipucords** between this project and the main project. I'd prefer we reference both using `qpc` as the shorthand.

# Completion checklist
To close this issue, the following items must be satisfied:
- [ ] Update all files, project names, and other references to use `qpc` instead of `qcs`
- [ ] Push all job updates to Jenkins

### PR DESCRIPTION
**Pull request by chambridge**

### CODE REVIEW

**Review by elyezer — COMMENTED** [review]
LGTM

```console
$ git grep -i qcs | wc -l
0

$ git grep -i qpc | wc -l
16
```

**Comment by elyezer** [comment]
I am going to manually rename the jobs on jenkins to follow the new nomenclature. JJB will create new jobs if we don't rename them.

**Comment by chambridge** [comment]
Ok. Feel free to "push" the jobs too if you like.

**Comment by elyezer** [comment]
I've updated the names on jenkins, now we can run JJB. Thank you @chambridge

**Pull request merged**
